services:
  mongodb:
    image: mongo
    container_name: mongodb-instance
    ports:
      - "27017:27017"
    networks:
      - my-network

  ewallet:
    build: ./
    container_name: ewallet-instance
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb-instance
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

    